spring:
  application:
    name: beer-query
#  data:
#    cassandra:
#      contactpoints: 127.0.0.1
#      keyspace-name: beer
#      port: 9042

server:
  port: 8091

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
